######################################################################
# Automatically generated by qmake (2.01a) Fr Mai 1 14:24:26 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GradingWindow.h
FORMS += GradingWindow.ui
SOURCES += GradingWindow.cpp main.cpp
